### ISSUE TITLE
Absolute wiki article name 

### ISSUE THREAD

**Issue by DRSDavidSoft** [cmderdev/cmder_wiki_files#2]
@daxgames, I suggest using absolute wiki articles instead of version-specific ones.

    Cmder 1.3.11 vs. ConEmu Default Settings

This is problematic, because Cmder version updates over time and the article name will get obsolete.
Since the GitHub wiki pages do not support redirects, this also prevents us from linking from the outside.

IMO, it's better to name the page this:

    Cmder vs. ConEmu Default Settings

Then, we can mention `as of Cmder v1.3.11 [...]` in the page body itself.

**Comment by daxgames** [comment]
Agree - it was just for a point of ref.

**Comment by DRSDavidSoft** [comment]
Thanks, I changed the page name to this:
https://github.com/cmderdev/cmder/wiki/Cmder-vs.-ConEmu

I might plan to update the page with additional differences between Cmder and ConEmu. Might come handy to refer to from the issues.

Closing this for now.
P.S. Can you also have a look at #1?
